version: '3.6'
# clean volumes: docker volume ls | grep -i local | gsed -e 's/^.*\(docker-.*\)$/\1/g' | xargs -J % docker volume rm %
services:
  db:
    image: mysql:5
    env_file: .env
    restart: always
    volumes:
      - ${PWD}/my_data/db:/var/lib/mysql:rw,delegated
    networks:
      - default

  app:
    image: invoiceninja/invoiceninja:alpine-4.5.22
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      -  ${PWD}/my_data/storage:/var/www/app/storage:rw,delegated
      -  ${PWD}/my_data/logo:/var/www/app/public/logo:rw,delegated
      -  ${PWD}/my_data/public:/var/www/app/public:rw,delegated
    networks: 
      - default  

  web:
    image: nginx:1
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      -  ${PWD}/my_data/storage:/var/www/app/storage:rw,delegated
      -  ${PWD}/my_data/logo:/var/www/app/public/logo:rw,delegated
      -  ${PWD}/my_data/public:/var/www/app/public:rw,delegated
    depends_on:
      - app
    ports:
      - 8000:80
    networks:
      - default
